//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HDTHANHTOANs = new HashSet<HDTHANHTOAN>();
        }
    
        public int MAKHACHHANG { get; set; }
        public Nullable<int> MAPHANCAP { get; set; }
        public Nullable<int> MANV { get; set; }
        public string HOTEN { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string CMND { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDTHANHTOAN> HDTHANHTOANs { get; set; }
        public virtual PCKHACHHANG PCKHACHHANG { get; set; }
    }
}
