//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int MANV { get; set; }
        public string TENNV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<bool> GT { get; set; }
        public Nullable<int> CMND { get; set; }
        public string CHUCVU { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    }
}
